### PR TITLE
increase sanic request timeout

### PR DESCRIPTION
**Pull request by zaibon**

### CODE REVIEW

**Comment by ahussein** [comment]
The test for hanging jobs is failing after this change.

**Comment by zaibon** [comment]
How does this test works?

**Comment by ahussein** [comment]
The test will execute an action the runs forever https://github.com/Jumpscale/ays9/blob/ea6468df6151ab593f4ddab3ca304c8ef011ec71/tests/sample_repo_recurring/actorTemplates/test_recurring_actions_1/actions.py#L27 and the test will then check if the job will timeout after the configured timeout. You can find the test here: https://github.com/Jumpscale/ays9/blob/master/tests/test_services/test_recurring_actions_hanging_jobs/actions.py

**Comment by zaibon** [comment]
Then I think there is a bug in the job timeout. Cause what I changed is the request timeout of sanic. But the job should still timeout if it has a timeout configured.

**Pull request merged**
